### ISSUE TITLE
Go Get Problem -  too many arguments in call to tsm1.NewCache

### ISSUE THREAD

**Issue by lasertiger** [Abc-Arbitrage/infix#10]
Hi, On Ubuntu 18.04 and 20.04, using go1.16.2 linux/amd64  when I install with:

go get -u github.com/Abc-Arbitrage/infix/command

**I get:**

# github.com/Abc-Arbitrage/infix/storage
ff_agent/build/go/pkg/mod/github.com/!abc-!arbitrage/infix@v0.0.0-20201217161219-cf00c58ef060/storage/rewriter.go:33:24: too many arguments in call to tsm1.NewCache
	have (uint64, string)
	want (uint64)

**Clean install looks like this:**
$ go get -u github.com/Abc-Arbitrage/infix/command
go: downloading github.com/Abc-Arbitrage/infix v0.0.0-20201217161219-cf00c58ef060
go: downloading github.com/golang/snappy v0.0.1
go: downloading github.com/influxdata/influxdb v1.5.5
go: downloading github.com/schollz/progressbar/v3 v3.7.2
go: downloading github.com/naoina/toml v0.1.1
go: downloading github.com/influxdata/influxql v1.1.0
go: downloading github.com/gogo/protobuf v1.3.1
go: downloading github.com/golang/snappy v0.0.3
go: downloading github.com/naoina/go-stringutil v0.1.0
go: downloading github.com/schollz/progressbar v1.0.0
go: downloading github.com/schollz/progressbar/v3 v3.7.6
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/influxdata/influxdb v1.8.4
go: downloading golang.org/x/crypto v0.0.0-20201112155050-0c6587e931a9
go: downloading github.com/mattn/go-runewidth v0.0.9
go: downloading github.com/mitchellh/colorstring v0.0.0-20190213212951-d06e56a500db
go: downloading github.com/mattn/go-runewidth v0.0.10
go: downloading golang.org/x/crypto v0.0.0-20210322153248-0c34fe9e7dc2
go: downloading golang.org/x/sys v0.0.0-20201113135734-0a15ea8d9b02
go: downloading golang.org/x/sys v0.0.0-20210324051608-47abb6519492
go: downloading github.com/RoaringBitmap/roaring v0.4.23
go: downloading github.com/cespare/xxhash v1.1.0
go: downloading go.uber.org/zap v1.14.1
go: downloading github.com/RoaringBitmap/roaring v0.5.5
go: downloading go.uber.org/zap v1.16.0
go: downloading golang.org/x/sync v0.0.0-20200317015054-43a5402ce75a
go: downloading golang.org/x/sync v0.0.0-20210220032951-036812b2e83c
go: downloading go.uber.org/atomic v1.6.0
go: downloading go.uber.org/multierr v1.5.0
go: downloading github.com/dgryski/go-bits v0.0.0-20180113010104-bd8a69a71dc2
go: downloading go.uber.org/atomic v1.7.0
go: downloading go.uber.org/multierr v1.6.0
go: downloading github.com/willf/bitset v1.1.10
go: downloading github.com/glycerine/go-unsnap-stream v0.0.0-20190901134440-81cf024a9e0a
go: downloading github.com/mschoch/smat v0.1.0
go: downloading github.com/tinylib/msgp v1.1.2
go: downloading github.com/glycerine/go-unsnap-stream v0.0.0-20210130063903-47dfef350d96
go: downloading github.com/willf/bitset v1.1.11
go: downloading github.com/mschoch/smat v0.2.0
go: downloading github.com/tinylib/msgp v1.1.5
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/jsternberg/zap-logfmt v1.2.0
go: downloading github.com/philhofer/fwd v1.0.0
go: downloading github.com/philhofer/fwd v1.1.1
go: downloading github.com/xlab/treeprint v1.0.0
go: downloading github.com/xlab/treeprint v1.1.0
go: downloading golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: downloading golang.org/x/time v0.0.0-20210220033141-f8bda1e9f3ba
go: downloading github.com/jwilder/encoding v0.0.0-20170811194829-b4e1701a28ef
go: downloading github.com/dgryski/go-bitstream v0.0.0-20180413035011-3522498ce2c8
go: downloading github.com/influxdata/influxql v1.1.1-0.20200828144457-65d3ef77d385
go: downloading github.com/influxdata/roaring v0.4.13-0.20180809181101-fc520f41fab6
go: downloading golang.org/x/term v0.0.0-20210220032956-6a3ed077a48d
go: downloading github.com/rivo/uniseg v0.2.0
go: downloading golang.org/x/term v0.0.0-20210317153231-de623e64d2a6
# github.com/Abc-Arbitrage/infix/storage
ff_agent/build/go/pkg/mod/github.com/!abc-!arbitrage/infix@v0.0.0-20201217161219-cf00c58ef060/storage/rewriter.go:33:24: too many arguments in call to tsm1.NewCache
	have (uint64, string)
	want (uint64)

**Comment by oktal** [comment]
Hello,

Thanks for reporting the issue.

It should be fixed now, could you retry ?

**Comment by oktal** [comment]
I'm closing this issue for now, please reopen if needed.
