### ISSUE TITLE
Build dependency problem with github.com/schollz/progressbar/v3

### ISSUE THREAD

**Issue by lasertiger** [Abc-Arbitrage/infix#11]
Hi, when I check out and run:

**dep ensure**

It's giving me:

**Solving failure: No versions of github.com/schollz/progressbar met constraints:
	v3.7.6: Could not introduce github.com/schollz/progressbar@v3.7.6, as its subpackage** github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.7.5: Could not introduce github.com/schollz/progressbar@v3.7.5, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.7.4: Could not introduce github.com/schollz/progressbar@v3.7.4, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.7.3: Could not introduce github.com/schollz/progressbar@v3.7.3, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.7.2: Could not introduce github.com/schollz/progressbar@v3.7.2, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.7.1: Could not introduce github.com/schollz/progressbar@v3.7.1, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.7.0: Could not introduce github.com/schollz/progressbar@v3.7.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.6.2: Could not introduce github.com/schollz/progressbar@v3.6.2, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.6.1: Could not introduce github.com/schollz/progressbar@v3.6.1, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.6.0: Could not introduce github.com/schollz/progressbar@v3.6.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.5.1: Could not introduce github.com/schollz/progressbar@v3.5.1, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.5.0: Could not introduce github.com/schollz/progressbar@v3.5.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.4.0: Could not introduce github.com/schollz/progressbar@v3.4.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.3.5: Could not introduce github.com/schollz/progressbar@v3.3.5, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.3.4: Could not introduce github.com/schollz/progressbar@v3.3.4, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.3.3: Could not introduce github.com/schollz/progressbar@v3.3.3, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.3.2: Could not introduce github.com/schollz/progressbar@v3.3.2, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.3.1: Could not introduce github.com/schollz/progressbar@v3.3.1, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.3.0: Could not introduce github.com/schollz/progressbar@v3.3.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.2.3: Could not introduce github.com/schollz/progressbar@v3.2.3, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.2.2: Could not introduce github.com/schollz/progressbar@v3.2.2, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.2.1: Could not introduce github.com/schollz/progressbar@v3.2.1, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.2.0: Could not introduce github.com/schollz/progressbar@v3.2.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.1.1: Could not introduce github.com/schollz/progressbar@v3.1.1, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.1.0: Could not introduce github.com/schollz/progressbar@v3.1.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.0.2: Could not introduce github.com/schollz/progressbar@v3.0.2, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.0.1: Could not introduce github.com/schollz/progressbar@v3.0.1, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v3.0.0: Could not introduce github.com/schollz/progressbar@v3.0.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.15.0: Could not introduce github.com/schollz/progressbar@v2.15.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.14.2: Could not introduce github.com/schollz/progressbar@v2.14.2, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.14.1: Could not introduce github.com/schollz/progressbar@v2.14.1, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.14.0: Could not introduce github.com/schollz/progressbar@v2.14.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.13.2: Could not introduce github.com/schollz/progressbar@v2.13.2, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.13.1: Could not introduce github.com/schollz/progressbar@v2.13.1, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.13.0: Could not introduce github.com/schollz/progressbar@v2.13.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.12.2: Could not introduce github.com/schollz/progressbar@v2.12.2, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.12.1: Could not introduce github.com/schollz/progressbar@v2.12.1, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.12.0: Could not introduce github.com/schollz/progressbar@v2.12.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.11.0: Could not introduce github.com/schollz/progressbar@v2.11.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.10.0: Could not introduce github.com/schollz/progressbar@v2.10.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.9.1: Could not introduce github.com/schollz/progressbar@v2.9.1, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.9.0: Could not introduce github.com/schollz/progressbar@v2.9.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.8.0: Could not introduce github.com/schollz/progressbar@v2.8.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.7.1: Could not introduce github.com/schollz/progressbar@v2.7.1, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.7.0: Could not introduce github.com/schollz/progressbar@v2.7.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.6.0: Could not introduce github.com/schollz/progressbar@v2.6.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.5.3: Could not introduce github.com/schollz/progressbar@v2.5.3, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.5.2: Could not introduce github.com/schollz/progressbar@v2.5.2, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.5.1: Could not introduce github.com/schollz/progressbar@v2.5.1, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.5.0: Could not introduce github.com/schollz/progressbar@v2.5.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.4.0: Could not introduce github.com/schollz/progressbar@v2.4.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.3.1: Could not introduce github.com/schollz/progressbar@v2.3.1, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.3.0: Could not introduce github.com/schollz/progressbar@v2.3.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.2.0: Could not introduce github.com/schollz/progressbar@v2.2.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.1.1: Could not introduce github.com/schollz/progressbar@v2.1.1, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.1.0: Could not introduce github.com/schollz/progressbar@v2.1.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v2.0.0: Could not introduce github.com/schollz/progressbar@v2.0.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v1.0.0: Could not introduce github.com/schollz/progressbar@v1.0.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v0.6.0: Could not introduce github.com/schollz/progressbar@v0.6.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v0.5.0: Could not introduce github.com/schollz/progressbar@v0.5.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v0.4: Could not introduce github.com/schollz/progressbar@v0.4, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v0.3.1: Could not introduce github.com/schollz/progressbar@v0.3.1, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v0.3.0: Could not introduce github.com/schollz/progressbar@v0.3.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v0.2.0: Could not introduce github.com/schollz/progressbar@v0.2.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	v0.1.0: Could not introduce github.com/schollz/progressbar@v0.1.0, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	master: Could not introduce github.com/schollz/progressbar@master, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	finish: Could not introduce github.com/schollz/progressbar@finish, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	percent: Could not introduce github.com/schollz/progressbar@percent, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	runewidth: Could not introduce github.com/schollz/progressbar@runewidth, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	spinners: Could not introduce github.com/schollz/progressbar@spinners, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)
	time: Could not introduce github.com/schollz/progressbar@time, as its subpackage github.com/schollz/progressbar/v3 is missing. (Package is required by (root).)

**Comment by oktal** [comment]
Hello,

Thanks for reporting the issue.

It should be fixed now, could you retry ?

**Comment by oktal** [comment]
I'm closing this issue for now, please reopen if needed.
